---
title: "Enunciados"
lang: es
format:
  html:
    toc: true
  typst:
    toc: true
    pdf-engine: typst
    papersize: a4
    margin:  {x: 1.75cm, y: 1.5cm}
execute:
  cache: true
editor: 
  markdown: 
    wrap: 72
---


## Problema 1
  
Aplicar los criterios de decisión bajo incertidumbre a el problema cuya tabla de decisión es la siguiente:

**favorable**

|     | E1  | E2  | E3  |
|-----|-----|-----|-----|
| D1  | 90  | 45  | -10 |
| D2  | 70  | 55  | 15  |
| D3  | 40  | 35  | 22  |

**desfavorable**

|     | E1  | E2  | E3  |
|-----|-----|-----|-----|
| D1  | -90 | -45 | 10  |
| D2  | -70 | -55 | -15 |
| D3  | -40 | -35 | -22 |

resuelverlo con cada uno de los métodos o funciones individuales de incertidumbre por separado (tanto en situación favorable como desfavorable)

## Problema 2 – Restaurante italiano y elección del menú

Un restaurante italiano debe decidir qué nuevo plato principal incluir en el menú de la próxima temporada. Las alternativas son:

-   **E1:** Lasagna vegetariana con verduras de temporada

-   **E2:** Risotto ai frutti di mare

-   **E3:** Ossobuco alla milanese con risotto a la milanesa

El éxito del plato depende de la preferencia de los clientes, es decir, de los **estados de la naturaleza**:

-   **S1:** Alta demanda de platos saludables y vegetarianos

-   **S2:** Preferencias equilibradas entre distintas opciones

-   **S3:** Mayor inclinación hacia la tradición italiana clásica

El restaurante estima los beneficios netos (en miles de euros) considerando los **ingresos obtenidos** por la venta del plato y los **costes de preparación** asociados.  
Así, por ejemplo:

- Bajo **S1**, la lasaña vegetariana (**E1**) genera ingresos de 120 000 € y tiene un coste de 40 000 €, obteniendo un beneficio de **80 000 €**.  
  En cambio, el risotto ai frutti de mare (**E2**) gana 110 000 € y gasta 40 000 €, resultando en **70 000 €**,  
  mientras que el ossobuco (**E3**) solo gana 70 000 € y gasta 40 000 €, quedando con **30 000 €**.

- Bajo **S2**, la lasaña obtiene **90 000 € de ingresos** y **40 000 € de costes**, por lo que gana **50 000 €**.  
  El risotto gana **100 000 €** y pierde **40 000 €**, quedando con **60 000 €**,  
  y el ossobuco gana **95 000 €** y pierde **40 000 €**, obteniendo **55 000 €**.
 
- Finalmente, bajo **S3**, la lasaña gana **60 000 €** y pierde **40 000 €**, quedando con **20 000 €**,  
  el risotto gana **80 000 €** y pierde **40 000 €**, quedando con **40 000 €**,  
  y el ossobuco gana **130 000 €** y pierde **40 000 €**, obteniendo **90 000 €**.

Determinar cuál es la mejor decisión para el restaurante aplicando la función R que devuelve la resolución de todos los métodos en una única tabla
